# Generated by Django 4.2.7 on 2023-11-25 10:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('birth_day', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('paid', models.IntegerField(blank=True, default=0, verbose_name='Paid')),
                ('have_debt', models.BooleanField(default=True)),
                ('voucher', models.FloatField(blank=True, default=0, verbose_name='Voucher')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('cost_or_price', models.IntegerField(help_text='Price')),
                ('how_much_sold', models.IntegerField(default=0)),
                ('avilable', models.BooleanField(default=True)),
                ('To_who', models.CharField(choices=[('0', 'Client'), ('1', 'Stuff')], default='0', max_length=1, verbose_name='The consumer?')),
                ('more', models.CharField(default='More', editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Person_identf', models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='ID')),
                ('EDU_state', models.CharField(blank=True, default=' ', max_length=300, null=True, verbose_name='Educational Level')),
                ('address', models.CharField(blank=True, default=' ', max_length=300, null=True)),
                ('img', models.ImageField(blank=True, upload_to='EMP Pic', verbose_name=' ')),
                ('cur_sallary', models.FloatField(verbose_name='Current Salary')),
                ('Date_of_join', models.DateField(default=datetime.datetime.now)),
                ('state_of_marrieg', models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widower', 'Widower')], max_length=300, verbose_name='Person state')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('phone_number_eme', models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency phone number')),
                ('more', models.CharField(default='More', editable=False, max_length=10)),
                ('job_postition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.jobposition')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid1, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_type', models.CharField(choices=[('Sick leave', 'Sick leave'), ('weekends', 'weekends')], max_length=300)),
                ('how_many_days', models.IntegerField(default=0, verbose_name='how many days')),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('The_amount', models.IntegerField(verbose_name='Amount')),
                ('the_reson', models.TextField(blank=True, null=True, verbose_name='reason')),
                ('img', models.ImageField(blank=True, upload_to='', verbose_name='Picture if there certificate[optional]')),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('specialty', models.ManyToManyField(blank=True, related_name='speciality', to='config.coursetype')),
            ],
            options={
                'verbose_name': 'Instructor',
            },
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('The_amount', models.IntegerField(verbose_name='Amount')),
                ('the_reson', models.TextField(blank=True, null=True, verbose_name='reason')),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('cost_forone', models.FloatField(blank=True, default=0, verbose_name='Course cost per person')),
                ('Voucher', models.FloatField(blank=True, default=0, verbose_name='Depreciation')),
                ('per_for_inst', models.FloatField(default=0, verbose_name='percentage for instructor')),
                ('Day_per_week', models.ManyToManyField(blank=True, related_name='Days', to='config.days')),
                ('Instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Thoth.instructors')),
                ('coursetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.coursetype')),
                ('groups', models.ManyToManyField(blank=True, related_name='Group', to='config.coursegroup')),
                ('levels', models.ManyToManyField(blank=True, related_name='levels', to='config.level')),
            ],
        ),
        migrations.CreateModel(
            name='ClintCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.coursegroup', verbose_name='Group')),
                ('the_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.client')),
                ('the_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.course')),
                ('the_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.level', verbose_name='Level')),
            ],
        ),
        migrations.CreateModel(
            name='ClientScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_score', models.IntegerField()),
                ('max_score', models.IntegerField()),
                ('the_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Thoth.client')),
                ('the_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Thoth.course')),
            ],
        ),
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_many_days', models.IntegerField(verbose_name='how many days')),
                ('Reson', models.TextField(blank=True, default=' ', verbose_name='reason')),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.employee')),
            ],
        ),
    ]
