# Generated by Django 4.2.7 on 2023-11-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clintcourses',
            name='Atten',
            field=models.TextField(blank=True, null=True),
        ),
    ]
