# Generated by Django 3.2.3 on 2023-11-06 17:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Person_identf', models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='ID')),
                ('EDU_state', models.CharField(blank=True, default=' ', max_length=300, null=True)),
                ('address', models.CharField(blank=True, default=' ', max_length=300, null=True)),
                ('img', models.FileField(upload_to='EMP Pic')),
                ('cur_sallary', models.FloatField(verbose_name='Salary')),
                ('state_of_marrieg', models.BooleanField(default=False, verbose_name='married?')),
            ],
        ),
        migrations.CreateModel(
            name='Peaple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('have_debt', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Recp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('cost_or_price', models.IntegerField(help_text='Price')),
                ('how_much_sold', models.IntegerField(default=0)),
                ('avilable', models.BooleanField(default=True)),
                ('more', models.CharField(default='More', editable=False, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_type', models.CharField(choices=[('Sick leave', 'Sick leave'), ('weekends', 'weekends')], max_length=300)),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_ticket', models.CharField(max_length=255)),
                ('ticket_price', models.FloatField()),
                ('he_paid', models.FloatField(default=0, help_text='How much did he paid from ticket')),
                ('have_debt', models.BooleanField(default=True)),
                ('time_added', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('the_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.peaple')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=datetime.datetime.now)),
                ('end_date', models.DateField(default=datetime.datetime.now)),
                ('coursetype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.coursetype')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('birth_day', models.DateField(default=datetime.datetime.now)),
                ('courses', models.ManyToManyField(blank=True, to='Thoth.Course')),
            ],
        ),
    ]
