# Generated by Django 3.2.3 on 2023-11-06 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0002_cafe_client_course_coursetype_employee_peaple_recp_service_ticket_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Date_of_join',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
