# Generated by Django 3.2.3 on 2023-11-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0003_employee_date_of_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='state_of_marrieg',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single'), ('Divorced', 'Divorced'), ('Widower', 'Widower')], max_length=300, verbose_name='Person state'),
        ),
    ]
