# Generated by Django 3.2.3 on 2023-11-06 18:18

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0005_alter_employee_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EDU_state',
            field=models.CharField(blank=True, default=' ', max_length=300, null=True, verbose_name='\tEducational Level'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, default=' ', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cur_sallary',
            field=models.FloatField(verbose_name='Current Salary'),
        ),
    ]
