# Generated by Django 3.2.3 on 2023-11-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0006_auto_20231106_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number_eme',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Emergency phone number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number'),
        ),
    ]
