# Generated by Django 3.2.3 on 2023-11-06 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
        ('Thoth', '0007_auto_20231106_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='job_postition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='config.jobposition'),
        ),
    ]
