# Generated by Django 3.2.3 on 2023-11-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0010_alter_employee_job_postition'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='more',
            field=models.CharField(default='More', editable=False, max_length=10),
        ),
    ]
