# Generated by Django 3.2.3 on 2023-11-07 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0011_employee_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('how_many_days', models.IntegerField(verbose_name='how many days')),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.employee')),
            ],
        ),
    ]
