# Generated by Django 3.2.3 on 2023-11-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0012_absent'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='how_many_days',
            field=models.IntegerField(default=0, verbose_name='how many days'),
        ),
    ]
