# Generated by Django 3.2.3 on 2023-11-07 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0013_vacation_how_many_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('The_amount', models.IntegerField(verbose_name='Amount')),
                ('the_reson', models.TextField(blank=True, null=True, verbose_name='reason')),
                ('Emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.employee')),
            ],
        ),
    ]
