# Generated by Django 3.2.3 on 2023-11-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0014_deduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
