# Generated by Django 3.2.3 on 2023-11-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0016_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(upload_to='EMP Pic', verbose_name=''),
        ),
    ]
