# Generated by Django 3.2.3 on 2023-11-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0018_auto_20231107_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='Levels', to='Thoth.Levels'),
        ),
    ]
