# Generated by Django 3.2.3 on 2023-11-10 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0019_auto_20231107_2042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Levels',
            new_name='Level',
        ),
        migrations.RemoveField(
            model_name='course',
            name='levels',
        ),
    ]
