# Generated by Django 3.2.3 on 2023-11-10 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_coursetype'),
        ('Thoth', '0020_auto_20231110_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructors',
            name='specialty',
            field=models.ManyToManyField(blank=True, related_name='speciality', to='config.CourseType'),
        ),
    ]
