# Generated by Django 3.2.3 on 2023-11-10 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0021_instructors_specialty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Level',
        ),
        migrations.AlterModelOptions(
            name='instructors',
            options={'verbose_name': 'Instructor'},
        ),
    ]
