# Generated by Django 3.2.3 on 2023-11-11 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0022_auto_20231111_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Thoth.instructors'),
        ),
    ]
