# Generated by Django 3.2.3 on 2023-11-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_level'),
        ('Thoth', '0024_alter_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='levels', to='config.Level'),
        ),
    ]
