# Generated by Django 3.2.3 on 2023-11-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0025_course_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cost_forone',
            field=models.FloatField(blank=True, default=0, verbose_name='cost foreach'),
        ),
    ]
