# Generated by Django 3.2.3 on 2023-11-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0027_alter_course_cost_forone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='the_person',
        ),
        migrations.AddField(
            model_name='client',
            name='paid',
            field=models.FloatField(blank=True, default=0, verbose_name='Paid'),
        ),
        migrations.DeleteModel(
            name='Peaple',
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
