# Generated by Django 3.2.3 on 2023-11-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0028_auto_20231111_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='have_debt',
            field=models.BooleanField(default=True),
        ),
    ]
