# Generated by Django 3.2.3 on 2023-11-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0029_client_have_debt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recp',
            new_name='Coffee',
        ),
        migrations.DeleteModel(
            name='Cafe',
        ),
    ]
