# Generated by Django 3.2.3 on 2023-11-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0030_auto_20231112_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EDU_state',
            field=models.CharField(blank=True, default=' ', max_length=300, null=True, verbose_name='Educational Level'),
        ),
    ]
