# Generated by Django 3.2.3 on 2023-11-12 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0032_course_day_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='per_for_inst',
            field=models.FloatField(default=0, verbose_name='percentage for instructor'),
        ),
    ]
