# Generated by Django 3.2.3 on 2023-11-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_group'),
        ('Thoth', '0033_course_per_for_inst'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='Group', to='config.Group'),
        ),
    ]
