# Generated by Django 3.2.3 on 2023-11-12 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0034_course_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='paid',
            field=models.IntegerField(blank=True, default=0, verbose_name='Paid'),
        ),
    ]
