# Generated by Django 3.2.3 on 2023-11-13 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0035_alter_client_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='courses',
        ),
        migrations.CreateModel(
            name='ClintCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.client')),
                ('the_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Thoth.course')),
            ],
        ),
    ]
