# Generated by Django 3.2.3 on 2023-11-13 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_group'),
        ('Thoth', '0037_absent_reson'),
    ]

    operations = [
        migrations.AddField(
            model_name='clintcourses',
            name='th_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.group'),
        ),
    ]
