# Generated by Django 3.2.3 on 2023-11-13 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_group'),
        ('Thoth', '0039_alter_clintcourses_th_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clintcourses',
            name='th_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.group', verbose_name='Group'),
        ),
    ]
