# Generated by Django 4.2.7 on 2023-11-14 19:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0040_alter_clintcourses_th_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='birth_day',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
