# Generated by Django 4.2.7 on 2023-11-14 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0008_paymentmethod'),
        ('Thoth', '0041_alter_client_birth_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='config.paymentmethod'),
        ),
    ]
