# Generated by Django 4.2.7 on 2023-11-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0042_client_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Voucher',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
