# Generated by Django 4.2.7 on 2023-11-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0044_alter_course_voucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Voucher',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
