# Generated by Django 4.2.7 on 2023-11-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0045_alter_course_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='voucher',
            field=models.FloatField(blank=True, default=0, verbose_name='Voucher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='Voucher',
            field=models.FloatField(blank=True, default=0, verbose_name='Depreciation'),
        ),
    ]
