# Generated by Django 4.2.7 on 2023-11-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0047_clintcourses_the_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='To_who',
            field=models.CharField(choices=[(0, 'Client'), (1, 'Stuff')], default=0, max_length=1, verbose_name='The consumer?'),
        ),
    ]
