# Generated by Django 4.2.7 on 2023-11-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0048_coffee_to_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
