# Generated by Django 4.2.7 on 2023-11-18 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0051_clientscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientscore',
            name='the_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Thoth.course'),
        ),
        migrations.AlterField(
            model_name='clientscore',
            name='the_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Thoth.client'),
        ),
    ]
