# Generated by Django 3.2.3 on 2023-11-01 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peaple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('cost_or_price', models.IntegerField(help_text='Price')),
                ('how_much_sold', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_ticket', models.CharField(max_length=255)),
                ('ticket_price', models.IntegerField()),
                ('he_paid', models.IntegerField(default=0, help_text='How much did he paid from ticket')),
                ('the_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.peaple')),
            ],
        ),
    ]
