# Generated by Django 3.2.3 on 2023-11-01 02:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='have_debt',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='time_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
