# Generated by Django 3.2.3 on 2023-11-01 02:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231101_0215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField()),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_added',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
