# Generated by Django 3.2.3 on 2023-10-31 03:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20231101_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='he_paid',
            field=models.FloatField(default=0, help_text='How much did he paid from ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
