# Generated by Django 3.2.3 on 2023-10-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20231031_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='peaple',
            name='have_debt',
            field=models.BooleanField(default=False),
        ),
    ]
