# Generated by Django 3.2.3 on 2023-10-31 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_peaple_have_debt'),
    ]

    operations = [
        migrations.AddField(
            model_name='recp',
            name='more',
            field=models.CharField(default='More', max_length=255),
        ),
        migrations.AlterField(
            model_name='recp',
            name='how_much_sold',
            field=models.IntegerField(default=0),
        ),
    ]
