# Generated by Django 3.2.3 on 2023-10-31 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20231031_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='recp',
            name='avilable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='recp',
            name='more',
            field=models.CharField(default='More', editable=False, max_length=255),
        ),
    ]
