# Generated by Django 3.2.3 on 2023-10-31 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20231031_0413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Recption', models.BooleanField(default=True)),
                ('Peaple', models.BooleanField(default=True)),
                ('Ticket', models.BooleanField(default=True)),
                ('Token', models.BooleanField(default=True)),
            ],
        ),
    ]
