# Generated by Django 3.2.3 on 2023-11-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_coursetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Level', models.CharField(max_length=255)),
            ],
        ),
    ]
