# Generated by Django 3.2.3 on 2023-11-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0004_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
