# Generated by Django 3.2.3 on 2023-11-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Thoth', '0040_alter_clintcourses_th_group'),
        ('config', '0005_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='CourseGroup',
        ),
    ]
