# Generated by Django 4.2.7 on 2023-11-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_rename_group_coursegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('time_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
