# Generated by Django 4.2.7 on 2023-11-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_cashout'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paymentname', models.CharField(max_length=255, verbose_name='payment method:')),
            ],
        ),
    ]
